---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.1
    driver:
      customize:
        memory: 1024

suites:
  - name: general
    run_list:
      - recipe[flashcards-cookbook::general]
    attributes:
