---
driver:
  name: vagrant
  provision: true

driver_config:
  ssh:
    username: root
    password: vagrant
    insert_key: true

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.1
    driver:
      customize:
        memory: 1024

suites:
  - name: general
    run_list:
      - recipe[flashcards-cookbook::general]

  - name: application
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: test/my_secret_key
    run_list:
      - recipe[flashcards-cookbook::application]

  - name: deploy
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: test/my_secret_key
    run_list:
      - recipe[flashcards-cookbook::application]
      - recipe[flashcards-cookbook::database]
      - recipe[flashcards-cookbook::redis]
      - recipe[flashcards-cookbook::deploy]

  - name: database
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: test/my_secret_key
    run_list:
      - recipe[flashcards-cookbook::database]

  - name: elasticsearch
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: test/my_secret_key
    run_list:
      - recipe[flashcards-cookbook::elasticsearch]

  - name: kibana
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: test/my_secret_key
    run_list:
      - recipe[flashcards-cookbook::kibana]

  - name: redis
    run_list:
      - recipe[flashcards-cookbook::redis]
