---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.1
    driver:
      customize:
        memory: 1024

suites:
  - name: general
    run_list:
      - recipe[flashcards-cookbook::general]
    attributes:

  - name: database
    data_bags_path: ../../data_bags
    encrypted_data_bag_secret_key_path: ../../.chef/my_secret_key
    run_list:
      - recipe[flashcards-cookbook::database]
    attributes:
      application:
        name: flashcards
        environment: development

  - name: elasticsearch
    data_bags_path: ../../data_bags
    encrypted_data_bag_secret_key_path: ../../.chef/my_secret_key
    run_list:
      - recipe[flashcards-cookbook::elasticsearch]
    attributes:
      java:
        jdk_version: 8

  - name: kibana
    data_bags_path: ../../data_bags
    encrypted_data_bag_secret_key_path: ../../.chef/my_secret_key
    run_list:
      - recipe[flashcards-cookbook::kibana]
    attributes:

  - name: redis
    run_list:
      - recipe[flashcards-cookbook::redis]
    attributes:
