name             'flashcards-cookbook'
maintainer       'Ilya Dolgirev'
maintainer_email 'ilya.dolgirev@gmail.com'
license          'All rights reserved'
description      'Installs/Configures flashcards mkdev.me course app'
long_description 'Installs/Configures flashcards mkdev.me course app'
version          '0.1.0'

depends 'build-essential'
depends 'ruby_build'
depends 'postgresql'
depends 'database'
depends 'redisio'
depends 'java'
depends 'elasticsearch'
depends 'simple-kibana'
depends 'nginx'
depends 'htpasswd'
depends 'imagemagick'
depends 'phantomjs'
depends 'chef-vault'

