name             'flashcards-cookbook'
maintainer       'Ilya Dolgirev'
maintainer_email 'ilya.dolgirev@gmail.com'
license          'All rights reserved'
description      'Installs/Configures flashcards mkdev.me course app'
long_description 'Installs/Configures flashcards mkdev.me course app'
version          '0.1.0'


depends 'apt', '~> 2.9.2'
depends 'build-essential', '~> 2.2.4'
depends 'git', '~> 4.3.5'
depends 'rbenv', '~> 1.7.1'
# depends 'postgresql', '~> 3.4.24'
depends 'postgresql', '~> 4.0.0'
depends 'database', '~> 4.0.9'
depends 'redisio', '~> 2.3.0'
depends 'java', '~> 1.36.0'
depends 'elasticsearch', '~> 2.1.0'
# depends 'kibana', '~> 0.1.9'
depends 'simple-kibana', '~> 0.4.3'
depends 'nginx', '~> 2.7.6'

